version: "3.8"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/pgdata/
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - "5432:5432"
    networks:
      - my_network

  web:
    image: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - static:/app/static
      - media:/app/media
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - my_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/app/static:ro
      - media:/app/media:ro
    links:
      - web
    depends_on:
      - web
    networks:
      - my_network

volumes:
  pgdata: { }
  static: { }
  media: { }

networks:
  my_network:
    driver: bridge
