version: "3.8"

services:
  web:
    image: web
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - .:/app/
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    image: docker.io/nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    links:
      - web
    depends_on:
      - web

networks:
  my_network:
    driver: bridge
